name: Main

on:
  pull_request:
  push:
    branches:
      - master
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  BOOST_DIR: "boost/boost"
  BOOST_VERSION: 1_79_0

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install ruff
        run: |
          pip install ruff

      - name: Run ruff linting
        run: |
          ruff check .

      - name: Run ruff formatting check
        run: |
          ruff format --check .

  tests-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install boost
        run: |
          sudo apt-get update && sudo apt-get install -y libboost-dev

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Test C-code
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j
          ./test
          cd ..

  build-wheels-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "cp310-manylinux_x86_64"
          - os: ubuntu-latest
            python-version: "cp311-manylinux_x86_64"
          - os: ubuntu-latest
            python-version: "cp312-manylinux_x86_64"
          - os: ubuntu-latest
            python-version: "cp313-manylinux_x86_64"
          - os: windows-latest
            python-version: "cp310-win_amd64"
          - os: windows-latest
            python-version: "cp311-win_amd64"
          - os: windows-latest
            python-version: "cp312-win_amd64"
          - os: windows-latest
            python-version: "cp313-win_amd64"
          - os: macos-13
            python-version: "cp310-macosx_x86_64"
          - os: macos-13
            python-version: "cp311-macosx_x86_64"
          - os: macos-13
            python-version: "cp312-macosx_x86_64"
          - os: macos-13
            python-version: "cp313-macosx_x86_64"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Boost
        uses: ./.github/actions/install-boost
        with:
          os: ${{ matrix.os }}
          boost-dir: ${{ env.BOOST_DIR }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: ${{ matrix.python-version }}
          CIBW_ENVIRONMENT: BOOST_DIR=${{ env.BOOST_DIR }}
          CIBW_BEFORE_TEST: pip install pytest
          CIBW_TEST_COMMAND: pytest {project}/tests/python
        with:
          output-dir: dist/

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
          name: "distributions"

  build-sdist:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    env:
      SDIST_FORMATS: gztar
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          pip install pybind11

      - name: Build source distribution
        run: |
          python setup.py sdist --formats ${SDIST_FORMATS} --dist-dir dist/

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
          name: distributions

  all-green-before-merge: # This job does nothing and is only used for the branch protection
    if: always()

    needs:
      - lint-and-format
      - tests-c
      - build-wheels-and-test

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  deploy:
    # We only want to run the deploy job if we've just created a version tag. in `on.push.tags`
    # we've specified to only this workflow on specific tags (and the main branch and pull
    # requests), so here we only need to check if we've been triggered from a tag
    if: startsWith(github.ref, 'refs/tags')
    environment: PyPI
    runs-on: ubuntu-latest
    needs: [build-wheels-and-test, build-sdist]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: distributions
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: ${{ secrets.PYPI_REPOSITORY_URL }}
